name: Update profile README with the latest YouTube Videos

on:
  schedule:
    # - cron: '0 17 * * 2'
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update README with the latest YouTube videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: node ./scripts/updateReadmeWithYoutubeLatestVideos.js
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "jesuslagaresgalan@gmail.com"
          git config --global user.name "Jesús Lagares"
          git add README.md
          git commit -m "Updated README with the latest YouTube videos" -a || echo "No changes to commit"
          git push
